name: production testing pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build, Test & Deploy Portfolio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Files Exist
      run: |
        test -f Devops-CI-CD/Test_Code/index.html || (echo "index.html missing" && exit 1)
        test -f Devops-CI-CD/Test_Code/style.css || (echo "style.css missing" && exit 1)
        test -f Devops-CI-CD/Test_Code/script.js || (echo "script.js missing" && exit 1)

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIARRIKGXVLHW773UBX
        aws-secret-access-key: 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
        aws-region: 'ap-south-1'

    - name: Deploy to S3
      run: |
        aws s3 sync Devops-CI-CD/Test_Code/ s3://secrets.react-app-sravan --delete
